spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/piedrazul_dev?currentSchema=public}
    username: ${DB_USERNAME:piedrazul_user}
    password: ${DB_PASSWORD:piedrazul_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8180/realms/piedrazul}
keycloak:
  admin:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8180}
    realm: ${KEYCLOAK_REALM:piedrazul}
    client-id: ${KEYCLOAK_CLIENT_ID:piedrazul-backend}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:X7Ef99AJnumJQlqArO919NCTT4O63RaP}


app:
  cors:
    allowed-origin-patterns: ["*"]
  rate-limiting:
    public-policies:
      - id: public-register-paciente
        method: POST
        path: /api/v1/auth/register/paciente
        capacity: 2000
        window: 1m
    paciente-policies:
      - id: paciente-medicos
        method: GET
        path: /api/v1/medicos
        capacity: 600
        window: 1m
      - id: paciente-medicos-configuracion
        method: GET
        path: /api/v1/medicos/*/configuracion
        capacity: 300
        window: 1m
      - id: paciente-pacientes-id
        method: GET
        path: /api/v1/pacientes/*
        capacity: 300
        window: 1m
      - id: paciente-citas-autonomo
        method: POST
        path: /api/v1/citas/autonomo
        capacity: 200
        window: 1m
      - id: paciente-disponibilidad-primera
        method: GET
        path: /api/v1/citas/disponibilidad/primera
        capacity: 600
        window: 1m
      - id: paciente-disponibilidad-primera-global
        method: GET
        path: /api/v1/citas/disponibilidad/primera/global
        capacity: 300
        window: 1m
      - id: paciente-disponibilidad-franjas
        method: GET
        path: /api/v1/citas/disponibilidad/franjas
        capacity: 600
        window: 1m

logging:
  level:
    com.piedrazul: DEBUG
    org.keycloak: DEBUG